/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'device_msc_dual_lun.release+E7-HP' 
 * Target:  'release+E7-HP' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* AlifSemiconductor::CMSIS Driver:USART@2.0.0 */
#define RTE_Drivers_USART               /* Driver UART  */
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@2.0.0 */
#define RTE_Drivers_IO              /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.0.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */


#endif /* RTE_COMPONENTS_H */
