/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0
 *
 * Project: 'device_cdc_msc_freertos.release+DevKit-E7-E3-HE' 
 * Target:  'release+DevKit-E7-E3-HE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "alif.h"

/* ARM::RTOS&FreeRTOS:Config&FreeRTOS@11.2.0 */
#define RTE_RTOS_FreeRTOS_CONFIG        /* RTOS FreeRTOS Config for FreeRTOS API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@11.2.0 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@11.2.0 */
#define RTE_RTOS_FreeRTOS_HEAP_4        /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Timers@11.2.0 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* AlifSemiconductor::CMSIS Driver:USART@2.1.0 */
#define RTE_Drivers_USART               /* Driver UART  */
/* AlifSemiconductor::Device:SOC Peripherals:GPIO@2.1.0 */
#define RTE_Drivers_IO              /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@2.1.0 */
#define RTE_Drivers_LL_PINCONF              /* Driver PinPAD and PinMux */


#endif /* RTE_COMPONENTS_H */
